management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

spring:
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO
    org.springframework.web: INFO